// Overworld generation data from the client biome definitions and item metadata.
// Blob coordinates follow LoadGenericBiomeMap: Unity bottom-up pixels, x first.
use super::{BiomeDefinition, ObjectDefinition};
pub const BLOB_MAP: [[u8; 36]; 36] = [
    [
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5,
    ],
    [
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5,
    ],
    [
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5,
    ],
    [
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5,
    ],
    [
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5,
    ],
    [
        0, 0, 0, 6, 6, 6, 1, 1, 1, 7, 7, 7, 2, 2, 2, 2, 2, 8, 8, 8, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
        4, 5, 5, 5, 9, 9,
    ],
    [
        6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 8, 8, 8, 8, 8, 8, 8, 4, 4, 11, 11,
        11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11,
        11, 11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 10, 8, 8, 8, 8, 8, 8, 11, 11, 11,
        11, 11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 10, 8, 8, 8, 8, 8, 8, 11, 11, 11,
        11, 11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 10, 10, 10, 10, 10, 8, 8, 8, 8, 8, 8, 11, 11, 11,
        11, 11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        6, 6, 12, 12, 12, 12, 7, 7, 7, 7, 7, 7, 7, 10, 10, 10, 13, 13, 13, 8, 8, 8, 8, 8, 11, 11,
        14, 14, 11, 11, 9, 9, 9, 9, 9, 9,
    ],
    [
        12, 12, 12, 12, 12, 12, 12, 7, 7, 15, 15, 15, 13, 13, 13, 13, 13, 13, 13, 16, 16, 8, 8, 8,
        14, 14, 14, 14, 14, 14, 9, 9, 9, 9, 17, 17,
    ],
    [
        12, 12, 12, 12, 12, 12, 12, 15, 15, 15, 15, 15, 13, 13, 13, 13, 13, 13, 13, 16, 16, 16, 16,
        16, 14, 14, 14, 14, 14, 14, 17, 17, 17, 17, 17, 17,
    ],
    [
        12, 12, 12, 12, 12, 12, 12, 15, 15, 15, 15, 15, 13, 13, 13, 13, 13, 13, 13, 16, 16, 16, 16,
        16, 14, 14, 14, 14, 14, 14, 17, 17, 17, 17, 17, 17,
    ],
    [
        12, 12, 12, 12, 12, 12, 15, 15, 15, 15, 15, 15, 13, 13, 13, 13, 13, 13, 16, 16, 16, 16, 16,
        16, 14, 14, 14, 14, 14, 17, 17, 17, 17, 17, 17, 17,
    ],
    [
        12, 12, 12, 12, 12, 12, 15, 15, 15, 15, 15, 15, 13, 13, 13, 13, 13, 13, 16, 16, 16, 16, 16,
        16, 16, 14, 14, 14, 14, 17, 17, 17, 17, 17, 17, 17,
    ],
    [
        18, 18, 12, 12, 12, 12, 19, 19, 19, 15, 15, 15, 13, 13, 13, 13, 13, 13, 16, 16, 16, 16, 16,
        16, 16, 14, 14, 14, 20, 20, 20, 17, 17, 17, 17, 17,
    ],
    [
        18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 13, 13, 13, 21, 21, 21, 16, 16, 22, 22, 16,
        16, 16, 20, 20, 20, 20, 20, 20, 23, 23, 23, 17, 17,
    ],
    [
        18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22,
        16, 16, 20, 20, 20, 20, 20, 23, 23, 23, 23, 23, 23,
    ],
    [
        18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22,
        22, 20, 20, 20, 20, 20, 20, 23, 23, 23, 23, 23, 23,
    ],
    [
        18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22,
        22, 20, 20, 20, 20, 20, 20, 23, 23, 23, 23, 23, 23,
    ],
    [
        18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22,
        22, 20, 20, 20, 20, 20, 20, 20, 23, 23, 23, 23, 23,
    ],
    [
        24, 24, 24, 18, 18, 18, 18, 19, 19, 19, 25, 25, 25, 26, 26, 21, 21, 21, 21, 22, 22, 22, 22,
        22, 20, 20, 27, 27, 20, 20, 20, 23, 23, 23, 28, 28,
    ],
    [
        24, 24, 24, 24, 24, 18, 18, 25, 25, 25, 25, 25, 25, 26, 26, 26, 21, 21, 21, 29, 29, 29, 22,
        22, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28,
    ],
    [
        24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 29, 29, 29, 29, 29,
        29, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28,
    ],
    [
        24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 29, 29, 29, 29, 29,
        29, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28,
    ],
    [
        24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 29, 29, 29, 29, 29,
        29, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28,
    ],
    [
        24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 29, 29, 29, 29, 29,
        29, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28,
    ],
    [
        24, 24, 30, 30, 30, 30, 30, 31, 31, 31, 25, 25, 32, 32, 32, 26, 26, 26, 33, 33, 29, 29, 29,
        29, 34, 34, 27, 27, 27, 27, 28, 28, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32, 32, 32, 26, 26, 33, 33, 33, 33, 33,
        33, 34, 34, 34, 34, 27, 27, 35, 35, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
        33, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
        33, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
        33, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33,
        34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35,
    ],
    [
        30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33,
        34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35,
    ],
];
pub const BIOMES: [BiomeDefinition; 10] = [
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 6,
        scenic_budget: (1, 2),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "alligator",
            "ant",
            "bat",
            "bear",
            "beaver",
            "bunny",
            "chicken",
            "chimpanzee",
            "duck",
            "dwarf",
            "frog",
            "goat",
            "goose",
            "gorilla",
            "horse",
            "human",
            "kitten",
            "pig",
            "poodle",
            "racoon",
            "sloth",
            "snail",
            "snake",
            "spider",
            "squirrel",
            "tiger",
            "trex",
            "wasp",
            "wolf",
            "hummingbird",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Berry Bush",
                is_item: true,
                rarity: 1,
                clump: (1, 3),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Mossy Tree",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Metal Vein",
                is_item: true,
                rarity: 1,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Ancient Pillars",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Nuts",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Mossy Tree",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Pond",
                is_item: false,
                rarity: 2,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Beehive",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 15.0,
            },
            ObjectDefinition {
                name: "Cotton Plant",
                is_item: true,
                rarity: 2,
                clump: (3, 5),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Grass Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Large Metal Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Metal Vein",
                dont_rotate: false,
                min_depth: 25.0,
            },
            ObjectDefinition {
                name: "Large Emerald Vein",
                is_item: true,
                rarity: 3,
                clump: (2, 3),
                clump_overwrite: "Emerald Vein",
                dont_rotate: false,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 2,
        scenic_budget: (1, 2),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "bear",
            "bunny",
            "yeti",
            "horse",
            "human",
            "moose",
            "owl",
            "polarBear",
            "santa",
            "squirrel",
            "wolf",
            "shark",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein (Snowy)",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Frozen Pond",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Titanium Vein",
                is_item: true,
                rarity: 1,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "MoonBerry Bush",
                is_item: true,
                rarity: 1,
                clump: (2, 2),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Frozen Tree",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Snowballs",
                is_item: true,
                rarity: 5,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Snowman",
                is_item: true,
                rarity: 2,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Snow Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Ice Shard Vein",
                is_item: true,
                rarity: 3,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 50.0,
            },
            ObjectDefinition {
                name: "Large Titanium Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Titanium Vein",
                dont_rotate: false,
                min_depth: 25.0,
            },
            ObjectDefinition {
                name: "Large Ice Shard Vein",
                is_item: true,
                rarity: 3,
                clump: (2, 3),
                clump_overwrite: "Ice Shard Vein",
                dont_rotate: false,
                min_depth: 25.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 2,
        scenic_budget: (0, 2),
        item_budget: (0, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "ant", "bat", "camel", "crab", "eagle", "elephant", "flamingo", "giraffe", "goat",
            "hippo", "horse", "human", "kangaroo", "lion", "ostrich", "rhino", "scorpion", "snake",
            "spider", "wasp", "wolf", "vulture", "peacock",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein (Desert)",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Gold Vein",
                is_item: true,
                rarity: 0,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Uranium Vein",
                is_item: true,
                rarity: 2,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Cactus",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Cotton Plant",
                is_item: true,
                rarity: 2,
                clump: (3, 5),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Desert Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Dark Shard Vein",
                is_item: true,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 50.0,
            },
            ObjectDefinition {
                name: "Hot Pepper Plant",
                is_item: true,
                rarity: 2,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Uranium Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Uranium Vein",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Large Dark Shard Vein",
                is_item: true,
                rarity: 3,
                clump: (1, 2),
                clump_overwrite: "Dark Shard",
                dont_rotate: false,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 3,
        scenic_budget: (2, 3),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "bear",
            "racoon",
            "moose",
            "salmon",
            "eagle",
            "crow",
            "hummingbird",
            "watermelon",
            "mantis",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Evergreen Tree",
                is_item: false,
                rarity: 5,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Tar Pit",
                is_item: false,
                rarity: 2,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Salmonberry Bush",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Gold Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Goldberry Bush",
                is_item: true,
                rarity: 2,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Red Mushroom",
                is_item: true,
                rarity: 1,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Brown Mushroom",
                is_item: false,
                rarity: 0,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Metal Vein",
                is_item: true,
                rarity: 1,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Evergreen Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Ruby Vein",
                is_item: true,
                rarity: 3,
                clump: (2, 3),
                clump_overwrite: "Ruby Vein",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Giant Red Mushroom",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Dug-up Red Mushroom",
                dont_rotate: false,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 1,
        scenic_budget: (0, 1),
        item_budget: (0, 0),
        dont_spawn_greens: true,
        copy_mobs_from: -1,
        mobs: &[
            "salmon",
            "narwhal",
            "crab",
            "starfish",
            "shark",
            "walrus",
            "turtle",
            "stingray",
            "seahorse",
            "pufferfish",
            "octopus",
            "dolphin",
            "seagull",
        ],
        objects: &[ObjectDefinition {
            name: "Stone Vein (Ocean)",
            is_item: false,
            rarity: 0,
            clump: (0, 0),
            clump_overwrite: "",
            dont_rotate: false,
            min_depth: 0.0,
        }],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 2,
        scenic_budget: (2, 2),
        item_budget: (0, 2),
        dont_spawn_greens: false,
        copy_mobs_from: 4,
        mobs: &[],
        objects: &[
            ObjectDefinition {
                name: "Spawner - Coconuts",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Palm Tree",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - White Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Blue Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Red Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Black Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Gold Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Purple Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Green Shells",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Ocean Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 2,
        scenic_budget: (1, 2),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "alligator",
            "crow",
            "frog",
            "komodoDragon",
            "octopus",
            "raptor",
            "spider",
            "snake",
            "trex",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Uranium Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Rotting Stump",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Brown Mushroom",
                is_item: true,
                rarity: 0,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Willow Tree",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Metal Vein",
                is_item: true,
                rarity: 0,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spiderhive",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 15.0,
            },
            ObjectDefinition {
                name: "Dug-up Purple Mushroom",
                is_item: true,
                rarity: 1,
                clump: (0, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Swamp Cave Entrance",
                is_item: false,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: true,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Large Amber Vein",
                is_item: true,
                rarity: 3,
                clump: (2, 3),
                clump_overwrite: "Amber Vein",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Giant Purple Mushroom",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Purple Mushroom",
                dont_rotate: false,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 1,
        scenic_budget: (0, 1),
        item_budget: (0, 0),
        dont_spawn_greens: true,
        copy_mobs_from: 6,
        mobs: &[],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Rotting Stump",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 0.0,
        texture_count: 2,
        scenic_budget: (1, 2),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "bear",
            "bunny",
            "carrot",
            "chinchilla",
            "corn",
            "cow",
            "duck",
            "eagle",
            "fox",
            "goose",
            "grasshopper",
            "horse",
            "hedgehog",
            "moose",
            "mouse",
            "racoon",
            "red panda",
            "shiba inu",
            "skunk",
            "snail",
            "squirrel",
            "tree",
            "wolf",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein (White)",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Birch Tree (Variant 2)",
                is_item: false,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Birch Tree (Variant 1)",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Nuts",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Brown Mushroom",
                is_item: true,
                rarity: 1,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Metal Vein",
                is_item: true,
                rarity: 0,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Silver Vein",
                is_item: true,
                rarity: 1,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Wheat",
                is_item: true,
                rarity: 0,
                clump: (0, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Pumpkin",
                is_item: true,
                rarity: 2,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Dug-up Giant Pumpkin",
                is_item: true,
                rarity: 3,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Large Silver Vein",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Silver Vein",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Giant Brown Mushroom",
                is_item: true,
                rarity: 2,
                clump: (2, 3),
                clump_overwrite: "Dug-up Brown Mushroom",
                dont_rotate: false,
                min_depth: 80.0,
            },
        ],
    },
    BiomeDefinition {
        min_depth: 100.0,
        texture_count: 1,
        scenic_budget: (1, 2),
        item_budget: (1, 1),
        dont_spawn_greens: false,
        copy_mobs_from: -1,
        mobs: &[
            "butterfly",
            "bunny",
            "chinchilla",
            "caterpillar",
            "chihuahua",
            "cookie",
            "corgi",
            "cupcake",
            "duck",
            "fox",
            "grasshopper",
            "hedgehog",
            "kitten",
            "ladybug",
            "mouse",
            "owl",
            "poodle",
            "pug",
            "red panda",
            "unicorn",
        ],
        objects: &[
            ObjectDefinition {
                name: "Stone Vein (Sakura)",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Sakura Tree",
                is_item: false,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Blue Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Red Blob",
                is_item: true,
                rarity: 1,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spawner - Sticks",
                is_item: true,
                rarity: 0,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Amethyst Vein",
                is_item: true,
                rarity: 2,
                clump: (1, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Sakura Pond",
                is_item: false,
                rarity: 2,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Lavender Bush",
                is_item: true,
                rarity: 0,
                clump: (0, 2),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Tea Tree",
                is_item: true,
                rarity: 1,
                clump: (0, 1),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Stone Lantern",
                is_item: false,
                rarity: 2,
                clump: (0, 0),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Titanium Vein (Sakura)",
                is_item: true,
                rarity: 1,
                clump: (2, 3),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
            ObjectDefinition {
                name: "Spirit Tree",
                is_item: true,
                rarity: 3,
                clump: (1, 2),
                clump_overwrite: "Spawner - Spirit Branch",
                dont_rotate: false,
                min_depth: 80.0,
            },
            ObjectDefinition {
                name: "Flowers",
                is_item: true,
                rarity: 0,
                clump: (2, 6),
                clump_overwrite: "",
                dont_rotate: false,
                min_depth: 0.0,
            },
        ],
    },
];
pub const PAINTS: &[&str] = &[
    "Basic Brown",
    "Glacier",
    "Basic White",
    "Basic Cyan",
    "Pinewood",
    "Basic Yellow",
    "Basic Blue",
    "Basic Green",
    "Basic Red",
    "Basic Pink",
    "Lavender Bloom",
    "Lavender Plum",
    "Olive Green",
    "Spirit Grey",
    "Basic Orange",
    "Hotdog Time",
    "Iron & Oak",
    "Basic Black",
    "Basic Purple",
    "Banana Bruise",
    "Winter Pastel",
    "Banana Dessert",
    "Pumpkin Orange",
    "Storm Grey",
    "Royal Red",
    "Candycane",
    "Utility Red",
    "Nomad Red",
    "Sludge",
    "Royal Sage",
    "Gold Leaf",
    "Crash-Pad Blue",
    "Mystic Dusk",
    "Forest Green",
    "Industrial Hazard",
    "Mystic Dawn",
    "Marble White",
    "Lumberjack",
    "Scottish Green",
    "King of Spades",
    "Black & Gold",
    "Titanium Trim",
    "Flaming Orange",
];
// All overworld spawn items use these four footprint types.
pub fn geometry_size(name: &str) -> i8 {
    match name {
        "Birch Tree (Variant 1)"
        | "Birch Tree (Variant 2)"
        | "Blue Blob"
        | "Dug-up Giant Pumpkin"
        | "Evergreen Tree"
        | "Frozen Tree"
        | "Large Mossy Tree"
        | "Mossy Tree"
        | "Palm Tree"
        | "Red Blob"
        | "Sakura Tree"
        | "Spirit Tree"
        | "Stone Vein"
        | "Stone Vein (Desert)"
        | "Stone Vein (Ocean)"
        | "Stone Vein (Sakura)"
        | "Stone Vein (Snowy)"
        | "Stone Vein (White)"
        | "Willow Tree" => 2,
        "Ancient Pillars"
        | "Desert Cave Entrance"
        | "Evergreen Cave Entrance"
        | "Grass Cave Entrance"
        | "Large Amber Vein"
        | "Large Dark Shard Vein"
        | "Large Emerald Vein"
        | "Large Ice Shard Vein"
        | "Large Metal Vein"
        | "Large Ruby Vein"
        | "Large Silver Vein"
        | "Large Stone Vein"
        | "Large Titanium Vein"
        | "Large Uranium Vein"
        | "Ocean Cave Entrance"
        | "Snow Cave Entrance"
        | "Swamp Cave Entrance" => 3,
        "Frozen Pond" | "Pond" | "Sakura Pond" | "Tar Pit" => 5,
        _ => 1,
    }
}
